### ISSUE TITLE
error "return RenameUnpickler(file_obj).load() TypeError: an integer is required (got type bytes)"

### ISSUE THREAD

**Issue by lihuiliullh** [UCLA-DM/GPT-GNN#46]
When I run the code, I meet the following error. Does anyone know how to solve it?

  File "GPT-GNN/example_OAG/GPT_GNN/data.py", line 274, in renamed_load
    return RenameUnpickler(file_obj).load()
TypeError: an integer is required (got type bytes)

**Comment by acbull** [comment]
May I know which data you try to load?

This part of code use pickle package for data serilization, and a naive way is to use the same version of my previous implementation

**Comment by lihuiliullh** [comment]
I use processed_OAG which is downloaded from https://drive.google.com/drive/folders/1a85skqsMBwnJ151QpurLFSa9o2ymc_rq

**Comment by lihuiliullh** [comment]
can you solve this problem? @acbull

**Comment by xp561** [comment]
metoo
